[package]
name = "submission"
version = "0.1.0"
edition = "2021"
default-run = "submission"

[[bin]]
name = "submission"
path = "submission.rs"

[dependencies]
itertools = "0.13.0"
proconio = { version = "0.5.0", features = ["derive"] }
# rand = "0.8.5"
