name: Lint shell

on:
  workflow_call:

jobs:
  shellcheck-and-shfmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: |
          sudo apt update &&
          sudo apt install -y shellcheck shfmt
      - run: ./.github/scripts/lint_shell.sh
        shell: bash
