name: Lint yaml

on:
  workflow_call:

jobs:
  yamllint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - run: pip install yamllint==1.38.0

      - run: yamllint .
